linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - nilerr
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
