version: 2
builds:
  - id: notesmd-cli
    binary: notesmd-cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: notesmd-cli
    homepage: https://github.com/Yakitrak/notesmd-cli
    repository:
      owner: Yakitrak
      name: homebrew-yakitrak
    commit_author:
      name: kartikayjainwal
      email: kartikayjainwal@gmail.com

scoops:
  - name: notesmd-cli
    homepage: https://github.com/Yakitrak/notesmd-cli
    repository:
      owner: Yakitrak
      name: scoop-yakitrak
    commit_author:
      name: kartikayjainwal
      email: kartikayjainwal@gmail.com

aurs:
  - name: notesmd-cli-bin
    homepage: https://github.com/Yakitrak/notesmd-cli
    description: Interact with Obsidian vaults from the terminal. Open, search, create, update and move notes!
    maintainers:
      - 'Kartikay Jainwal <kartikayjainwal at gmail dot com>'
      - 'Jonathan Neidel <aur at jneidel dot com>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/notesmd-cli-bin.git'
    package: |-
      install -Dm755 "./notesmd-cli" "${pkgdir}/usr/bin/notesmd-cli"
      ./notesmd-cli completion bash >notesmd-cli.bash
      ./notesmd-cli completion fish >notesmd-cli.fish
      ./notesmd-cli completion zsh >_notesmd-cli
      install -Dm644 notesmd-cli.bash "${pkgdir}/usr/share/bash-completion/completions/notesmd-cli"
      install -Dm644 notesmd-cli.fish "${pkgdir}/usr/share/fish/completions/notesmd-cli.fish"
      install -Dm644 _notesmd-cli "${pkgdir}/usr/share/zsh/site-functions/_notesmd-cli"


checksum:
  name_template: "checksums.txt"
